name: Build Client RSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the renderer application publish
        run: bun run build
        env:
          # 避免 macOS 构建图形问题
          CI: true

      - name: upload artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          path: out/make/*
