name: Build Client RSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }} # 使用矩阵策略，支持多平台构建

    strategy:
      matrix:
        os: [macos-latest] # 支持 Linux、Windows、macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出代码

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Make Electron app
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }} # artifact 名称
          path: out/make/* # 上传 out/make/ 目录下的构建产物（electron-forge 默认输出路径）

